### ISSUE TITLE
using Fetch API ?

### ISSUE THREAD

**Issue by Hgallien** [DoomDuck/transcendence#11]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
Do we need to use fetch or a equivalent API to communicate between front/back and maybee back/game?

**Comment by DoomDuck** [comment]
Yes this likely will be the case for the front however all requests are handled and dispatched by nestjs for the back.
I don't see where fetch api could be useful for the back at the moment.
But you can use it when testing though

**Comment by Hgallien** [comment]
Copy that
