### ISSUE TITLE
How organize project to make imports work ?

### ISSUE THREAD

**Issue by luckylu91** [DoomDuck/transcendence#16]
I have a `src/server`, a `src/client/` and a `src/common/` folder.
`server/` and `client/` have both a tsconfig.json and a webpack.config.json

Is `src/` the project root directory ?
How do I import code in `common/` in both `server/` and `client/` ?

**Comment by DoomDuck** [comment]
Maybe I will be able to use this to solve the problem with [this](https://webpack.js.org/configuration/resolve/#resolveroots)

**Comment by DoomDuck** [comment]
Done!
