### ISSUE TITLE
I get weird LSP errors about tsconfig & decorators

### ISSUE THREAD

**Issue by Hgallien** [DoomDuck/transcendence#62]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/78477764/179549452-c82a43ec-94d7-4866-9ff2-0b215410a889.png">

**Comment by Hgallien** [comment]
I found that changing `tsconfig.back.json` to `tsconfig.json` made the Lsp work

**Comment by DoomDuck** [comment]
Done !
